name: Build application assets

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "â˜ï¸ checkout repository"
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: "ğŸ”§ Setup Node.js"
        uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
          check-latest: true

      - name: "ğŸ“¦ Cache Node dependencies"
        uses: actions/cache@v2
        with:
          path: /tmp/node-cache
          key: ${{ runner.os }}-${{ hashFiles('**/package.lock') }}

      - name: "ğŸ“¦ Install NPM Dependencies"
        run: npm install

      - name: "ğŸ—ï¸ Compile assets for production"
        run: npm run production

      - name: "ğŸ¤– Commit new assets"
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Re-building assets for production
          file_pattern: public/**/*.css public/**/*.js
